source/PhluffyFotos.Web/ViewModels/AlbumViewModel.cs
namespace PhluffyFotos.Web.ViewModels
{
    using System.Collections.Generic;
    using PhluffyFotos.Data;

    public class AlbumViewModel
    {
        public IEnumerable<Album> Albums { get; set; }
        
        public string Owner { get; set; }
        
        public string Album { get; set; }
    }
}

source/PhluffyFotos.Web/Controllers/AlbumController.cs
namespace PhluffyFotos.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using PhluffyFotos.Data;
    using PhluffyFotos.Data.Exceptions;
    using PhluffyFotos.Data.WindowsAzure;
    using PhluffyFotos.Web.ViewModels;

    public class AlbumController : Controller
    {
        private IPhotoRepository repository;

        public AlbumController()
            : this(new PhotoRepository())
        {
        }

        public AlbumController(IPhotoRepository repository)
        {
            this.repository = repository;
        }

        public ActionResult Index()
        {
            AlbumViewModel albumViewModel = new AlbumViewModel();

            albumViewModel.Albums = this.repository.GetAlbums();

            return View(albumViewModel);
        }

        public ActionResult Get(string owner, string album)
        {
            if (string.IsNullOrEmpty(album))
            {
                return RedirectToAction("MyAlbums", new { owner = owner });
            }

            AlbumViewModel albumViewModel = new AlbumViewModel();
            PhotoViewModel photoViewModel = new PhotoViewModel();

            albumViewModel.Album = album;
            photoViewModel.Album = album;
            albumViewModel.Owner = owner.ToLowerInvariant();
            photoViewModel.Owner = owner.ToLowerInvariant();

            var albums = this.repository.GetAlbumsByOwner(owner.ToLowerInvariant());
            var foundAlbum = albums.SingleOrDefault(a => a.AlbumId == album || a.Title == album);

            if (foundAlbum != null)
            {
                photoViewModel.Photos = this.repository.GetPhotosByAlbum(owner, foundAlbum.AlbumId);
                return View(photoViewModel);
            }

            // no album found
            return View(new PhotoViewModel());
        }

        public ActionResult MyAlbums(string owner)
        {
            AlbumViewModel albumViewModel = new AlbumViewModel();
            PhotoViewModel photoViewModel = new PhotoViewModel();

            albumViewModel.Owner = owner.ToLowerInvariant();
            photoViewModel.Owner = owner.ToLowerInvariant();

            var albums = this.repository.GetAlbumsByOwner(owner.ToLowerInvariant());

            // if there are more than 1 album with photos for this user
            // then return a view of the albums for them
            if (albums.Where(a => a.HasPhotos).Count() > 1)
            {
                albumViewModel.Albums = albums;
                return View("Index", albumViewModel);
            }

            // if there is only 1 album, just return photos for it
            if (albums.Where(a => a.HasPhotos).Count() == 1)
            {
                photoViewModel.Photos = this.repository.GetPhotosByAlbum(owner, albums.First().AlbumId);
                return View("Get", photoViewModel);
            }

            // there are no albums for this user
            return View("Get", new PhotoViewModel());
        }

        [Authorize]
        public ActionResult Create()
        {
            return View(new AlbumCreateViewModel()
            {
                Title = "My Pics"
            });
        }

        [AcceptVerbs(HttpVerbs.Post), Authorize]
        public ActionResult Create(AlbumCreateViewModel album)
        {
            if (!ModelState.IsValid)
            {
                return View(album);
            }

            var owner = User.Identity.Name.ToLowerInvariant();
            if (this.repository.GetAlbumsByOwner(owner).FirstOrDefault(o => o.AlbumId == SlugHelper.GetSlug(album.Title)) != null)
            {
                ModelState.AddModelError("Title", "An album with the same name already exists.");
                return View(album);
            }

            this.repository.CreateAlbum(album.Title, owner);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Upload()
        {
            AlbumUploadViewModel albumViewModel = new AlbumUploadViewModel
            {
                Title = "Untitled"
            };

            albumViewModel.Albums = this.repository.GetAlbumsByOwner(User.Identity.Name.ToLowerInvariant());

            if (albumViewModel.Albums.Count() > 0)
            {
                return View(albumViewModel);
            }

            return RedirectToAction("Create");
        }

        [AcceptVerbs(HttpVerbs.Post), Authorize]
        public ActionResult Upload(AlbumUploadViewModel model)
        {
            if (Request.Files.Count != 1 || Request.Files[0].ContentLength == 0)
            {
                ModelState.AddModelError("Photo", "Provide a photo");
            }

            if (!ModelState.IsValid)
            {
                model.Albums = this.repository.GetAlbumsByOwner(User.Identity.Name.ToLowerInvariant());
                return View(model);
            }

            var photo = Request.Files[0];

            // generate a unique name
            string id = SlugHelper.GetSlug(model.Title);
            string owner = User.Identity.Name.ToLowerInvariant();
            string albumName = model.Album;

            try
            {
                this.repository.Add(
                                    new Photo()
                                    {
                                        AlbumId = albumName,
                                        Description = model.Description,
                                        Owner = owner,
                                        PhotoId = id,
                                        Title = model.Title,
                                        ThumbnailUrl = "/Content/images/processing.png",
                                        Url = "/Content/images/processing.png",
                                        RawTags = string.IsNullOrEmpty(model.Tags) ? "uncategorized" : model.Tags
                                    },
                                    photo.InputStream,
                                    photo.ContentType,
                                    photo.FileName);
            }
            catch (PhotoNameAlreadyInUseException)
            {
                ModelState.AddModelError("Title", "A picture with the same name already exists on this album");
                model.Albums = this.repository.GetAlbumsByOwner(User.Identity.Name.ToLowerInvariant());
                return View(model);
            }

            return RedirectToAction("Index", "Photo", new { owner = owner, album = model.Album, photoId = id });
        }

        public ActionResult Delete(string owner, string album)
        {
            if (User.IsInRole("Administrator") || User.Identity.Name.Equals(owner, StringComparison.OrdinalIgnoreCase))
            {
                this.repository.DeleteAlbum(album, owner);
            }

            return RedirectToAction("MyAlbums", new { owner = owner });
        }
    }
}

source/PhluffyFotos.Web/Views/Album/Create.cshtml
@model PhluffyFotos.Web.ViewModels.AlbumCreateViewModel

@{
    ViewBag.Title = "Create an Album";
}

@using (Html.BeginForm()) {
    <div id="lvl3">
        <label>Create an Album<br />
            @Html.TextBoxFor(m => m.Title)
            @Html.ValidationMessageFor(m => m.Title)
            @* @Html.TextBox("album", "My Pics", new { style="width: 240px" })
            @Html.ValidationMessage("album")*@
        </label>
        <br />
        <input type="submit" value="Submit" style="border: solid 1px 003399; background: #0063DC; color: #fff;" />
        <br />
        <br />
        <br />
        <br />
    </div>
} 



source/PhluffyFotos.Web/Views/Album/Get.cshtml
@model PhluffyFotos.Web.ViewModels.PhotoViewModel
@{
    ViewBag.Title = "Photos";
    var album = this.Model.Album;
    var owner = this.Model.Owner; 
}
<div id="lvl2">
</div>
<div id="lvl3">
    @if (this.Model.Photos == null)
    {
        <p>No photos available for this user</p>
    }
    else
    {
        <ul id="itemcontainer" class="photoList">
            @foreach (var item in this.Model.Photos)
            { 
                <li>
                    <div class="photoTitle">
                        <h2>
                            <span style="color: #888;">@item.Title</span></h2>
                    </div>
                    <br />
                    <a href="@Url.Action("Index", "Photo", new { owner = item.Owner, album = item.AlbumId, photoId = item.PhotoId })">
                        <img src="@item.ThumbnailUrl" alt="@item.Title" style="border:0" />
                    </a>
                    <br />
                    <em>Filed under:</em>
                    @if (!string.IsNullOrEmpty(item.RawTags))
                    {
                        foreach (var tag in item.RawTags.Split(';').Where(s => s.Trim().Length > 0).Select(s => s.Trim().ToLowerInvariant()))
                        { 
                        @Html.ActionLink(tag, "Search", new { controller = "Search", tag = tag }) @:;
                                            }
                    }
                    @if (User.IsInRole("Administrator") || User.Identity.Name.Equals(item.Owner, StringComparison.InvariantCultureIgnoreCase))
                    { 
                        <div class="admin">
                            @Html.ActionLink(
                                "Delete",
                                "Delete",
                                "Photo",
                                new { owner = item.Owner, album = item.AlbumId, photoId = item.PhotoId, },
                                new { onclick = "return confirm('Are you sure you want to delete this picture?'); " })
                        </div>
                    }
                    <br />
                </li>
            }
        </ul>
    }
</div>

source/PhluffyFotos.Web/Views/Album/Index.cshtml
@model PhluffyFotos.Web.ViewModels.AlbumViewModel

@{
    ViewBag.Title = "Index";
}

<div id="lvl2">
    @if (this.Model.Albums.Count() == 0) { 
        <p>No albums available</p>
    } else { 
        <div id="lvl3">
            <ul id="itemcontainer" class="photoList">
                @foreach (var item in this.Model.Albums) { 
                <li>
                    <div class="albumTitle">
                        <h2>@Html.ActionLink(item.Title, "Get", new { owner = item.Owner, album = item.AlbumId }) (by @Html.ActionLink(item.Owner, "Get", new { item.Owner }))</h2> 
                    </div>
                
                    @if (!string.IsNullOrEmpty(item.ThumbnailUrl)) { 
                        <a href="@Url.Action("Get", "Album", new { owner = item.Owner, album = item.AlbumId })">
                            <img src="@item.ThumbnailUrl" alt="@item.Title" />
                        </a>
                    } 
                                
                    <br />
                    <em>Owner:</em> @item.Owner
                    @if (User.IsInRole("Administrator") || User.Identity.Name.Equals(item.Owner, StringComparison.InvariantCultureIgnoreCase))
                    { 
                        <div class="admin">
                            @Html.ActionLink(
                                "Delete", 
                                "Delete",
                                "Album", 
                                new { owner = item.Owner, album = item.AlbumId },
                                new { onclick = "return confirm('Are you sure you want to delete this album?'); " })
                        </div>
                    } 
                </li>
                } 
            </ul>
        </div>
    } 
</div>



source/PhluffyFotos.Web/Views/Album/Upload.cshtml
@model PhluffyFotos.Web.ViewModels.AlbumUploadViewModel

@{
    ViewBag.Title = "Upload a Picture";
    var albums = this.Model.Albums;
}

<div id="lvl3">
    @using (Html.BeginForm("Upload", "Album", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "if ($(this).valid()) document.getElementById('UploadSubmitBtn').disabled = 'disabled'" }))
    { 
    <div id="uploadClmLeft">
        <p>
        <label>
                Select Photo <br />
                <input type="file" name="Photo" />
                <br />@Html.ValidationMessage("Photo")
            </label>
        </p>
        <p>
            <label>
            Select Album<br />
            @Html.DropDownListFor(
                m => m.Album, 
                Model.Albums.Select(a => new SelectListItem { Text = a.Title, Value = a.AlbumId, Selected = a.AlbumId == Model.Album }), 
                new { style = "width: 240px" })    
            </label>
        </p>
        <p>
            <label>
                Title<br />
                @Html.TextBoxFor(m => m.Title, new { style = "width: 240px" })
                <br />
                @Html.ValidationMessageFor(m => m.Title)
            </label>
        </p>
           
        <p>
            <label>
                Description<br />
                @Html.TextAreaFor(m => m.Description, new { style = "width: 240px", cols = 2, rows = 4 })
            </label>  
        </p>
            <p>
            <label>
                Tags<br />
                @Html.TextBoxFor(m => m.Tags, new { style = "width: 240px", })<br />
                <span>Add the tags as: <strong>vacations; family; "new york"</strong></span>
            </label>
        </p>
        <p>
            <input type="submit" style="border: solid 1px 003399; background: #0063DC; color: #fff;" value="Submit" id="UploadSubmitBtn" />
        </p>
    </div>
    <div id="uploadClmRight">
        <img src="@Url.Content("~/content/images/upload.png")" alt="Upload" />
    </div>
    } 
</div>    


