source/PhluffyFotos.Web/Controllers/PhotoController.cs
namespace PhluffyFotos.Web.Controllers
{
    using System;
    using System.Web.Mvc;
    using PhluffyFotos.Data;
    using PhluffyFotos.Data.WindowsAzure;

    public class PhotoController : Controller
    {
        private IPhotoRepository repository;

        public PhotoController()
            : this(new PhotoRepository())
        {
        }

        public PhotoController(IPhotoRepository repository)
        {
            this.repository = repository;
        }

        public ActionResult Index(string owner, string album, string photoId)
        {
            var photo = this.repository.GetPhotoByOwner(owner, album, photoId);

            return View(photo);
        }

        public ActionResult Delete(string owner, string album, string photoId)
        {
            if (User.IsInRole("Administrator") || User.Identity.Name.Equals(owner, StringComparison.OrdinalIgnoreCase))
            {
                this.repository.Delete(owner, album, photoId);
            }

            return RedirectToAction("Get", "Album", new { owner, album });
        }
    }
}

source/PhluffyFotos.Web/Controllers/SearchController.cs
namespace PhluffyFotos.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using PhluffyFotos.Data;
    using PhluffyFotos.Data.WindowsAzure;

    public class SearchController : Controller
    {
        private IPhotoRepository repository;

        public SearchController()
            : this(new PhotoRepository())
        {
        }

        public SearchController(IPhotoRepository repository)
        {
            this.repository = repository;
        }

        public ActionResult Search(string tag)
        {
            var results = this.repository.FindPhotosByTag(tag);

            return View(results);
        }

        public ActionResult Tag(string searchTerms)
        {
            // get all the tags
            var tags = searchTerms.Split(';')
                .Select(s => s.Trim().ToLowerInvariant())
                .ToArray();

            var results = this.repository.FindPhotosByTag(tags);

            return View("Search", results);
        }
    }
}

source/PhluffyFotos.Web/Views/Search/Search.cshtml
@model IEnumerable<PhluffyFotos.Data.Photo>

@{
    ViewBag.Title = "Search";
}

<div id="lvl2"></div>
<div id="lvl3">
    <ul id="itemcontainer" class="photoList">
        @if (this.Model.Count() != 0) { 
            foreach (var item in this.Model) { 
                <li>
                    <div class="photoTitle">
                        <h2><span style="color: #888;">@item.Title</span></h2>
                    </div>
                    <br />
                    <a href="@Url.Action("Index", "Photo", new { owner = item.Owner, photoId = item.PhotoId, album = item.AlbumId } )">
                        <img src="@item.ThumbnailUrl" alt="@item.Title" style="border:0" />
                    </a>
                    <br />
                    <em>Filed under:</em>
                        @if (!string.IsNullOrEmpty(item.RawTags))
                        {
                            foreach (var tag in item.RawTags.Split(';').Where(s => s.Trim().Length > 0).Select(s => s.Trim().ToLowerInvariant())) { 
                                @Html.ActionLink(tag, "Search", new { controller = "Search", tag = tag }) @:;
                            } 
                        } 
                    <br />
                </li>
            } 
        } else {
            <text>No Photos found...</text>
        } 
    </ul>
</div>


